baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Hugo Site'
theme = "ananke"

[menu]
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 1
	[[menu.main]]
		identifier = "categories"
		name = "Category"
		url = "/categories/"
		weight = 1

[taxonomies]
  category = "categories"
  tag = "tags"
